from django.conf.urls import url, include

from contacts.views import company, group, person

urlpatterns = [

    url(r'^companies/page/(?P<page>\d+)/$', company.list,
        name='contacts_company_list_paginated'),
    url(r'^companies/add/$', company.create,
        name='contacts_company_create'),
    url(r'^companies/(?P<pk>\d+)-(?P<slug>[-\w]+)/delete/$',
        company.delete, name='contacts_company_delete'),
    url(r'^companies/(?P<pk>\d+)/delete/$', company.delete,
        name='contacts_company_delete'),
    url(r'^companies/(?P<pk>\d+)-(?P<slug>[-\w]+)/edit/$',
        company.update, name='contacts_company_update'),
    url(r'^companies/(?P<pk>\d+)/edit/$', company.update,
        name='contacts_company_update'),
    url(r'^companies/(?P<pk>\d+)-(?P<slug>[-\w]+)/$',
        company.detail, name='contacts_company_detail'),
    url(r'^companies/(?P<pk>\d+)/$', company.detail,
        name='contacts_company_detail'),
    url(r'^companies/$', company.list, name='contacts_company_list'),

    url(r'^people/page/(?P<page>\d+)/$', person.list,
        name='contacts_person_list_paginated'),
    url(r'^people/add/$', person.create, name='contacts_person_create'),
    url(r'^people/(?P<pk>\d+)-(?P<slug>[-\w]+)/delete/$', person.delete,
        name='contacts_person_delete'),
    url(r'^people/(?P<pk>\d+)/delete/$', person.delete,
        name='contacts_person_delete'),
    url(r'^people/(?P<pk>\d+)-(?P<slug>[-\w]+)/edit/$', person.update,
        name='contacts_person_update'),
    url(r'^people/(?P<pk>\d+)/edit/$', person.update,
        name='contacts_person_update'),
    url(r'^people/(?P<pk>\d+)-(?P<slug>[-\w]+)/$', person.detail,
        name='contacts_person_detail'),
    url(r'^people/(?P<pk>\d+)/$', person.detail,
        name='contacts_person_detail'),
    url(r'^people/$', person.list, name='contacts_person_list'),

    url(r'^groups/page/(?P<page>\d+)/$', group.list,
        name='contacts_group_list_paginated'),
    url(r'^groups/add/$', group.create,
        name='contacts_group_create'),
    url(r'^groups/(?P<pk>\d+)-(?P<slug>[-\w]+)/delete/$', group.delete,
        name='contacts_group_delete'),
    url(r'^groups/(?P<pk>\d+)/delete/$', group.delete,
        name='contacts_group_delete'),
    url(r'^groups/(?P<pk>\d+)-(?P<slug>[-\w]+)/edit/$', group.update,
        name='contacts_group_update'),
    url(r'^groups/(?P<pk>\d+)/edit/$', group.update,
        name='contacts_group_update'),
    url(r'^groups/(?P<pk>\d+)-(?P<slug>[-\w]+)/$', group.detail,
        name='contacts_group_detail'),
    url(r'^groups/(?P<pk>\d+)/$', group.detail,
        name='contacts_group_detail'),
    url(r'^groups/$', group.list, name='contacts_group_list'),
]
